services:
  # Node.js Service
  - type: web
    name: nodejs-server
    env: node
    buildCommand: 'npm install'
    startCommand: 'npm start'
    plan: free
    branches: 
      - main
    routes:
      - "/": index.js  # Replace with your Node.js entry point
  
  # Python Service
  - type: web
    name: python-service
    env: python
    buildCommand: 'pip install -r requirements.txt'  # Install Python dependencies
    startCommand: 'python3 controller/script.py'    # Run your Python script
    plan: free
    branches: 
      - main
