services:
  # Node.js Service
  - type: web
    name: nodejs-server
    env: node
    buildCommand: 'npm install && pip install -r requirements.txt'
    startCommand: 'node index.js'  # Start your Node.js server, which will trigger the Python script
    plan: free
    branches: 
      - main
    routes:
      - "/": index.js  # Replace with your Node.js entry point
